spring:
  application:
    name: event
nacos:
  config:
    group: event
    namespace: 2ee6c5ee-a2d2-474e-8686-56fad0ff0632
    server-addr: 49.233.54.55:8848
    auto-refresh: true
    bootstrap:
      enable: true
      log-enable: true
    type: yaml
    #data-id: application
    data-ids: application-druid, application

